### ISSUE TITLE
Installation failed on Buster / Node-Red 1.03

### ISSUE THREAD

**Issue by Inxession** [HendrikRoth/node-red-contrib-oled#17]
Hello,

tried very often to Install this Node to my Node-Red 1.03 on up to Date Raspbian.
But the Installation fails. See the attached Log File.
I have no idea whats the specified Problem.

The OLED Display works great via Python Script, but i want to use it with Node Red.

Hope any one can help me soon.

Thanks a lot.
[2020-04-01T08_03_58_120Z-debug.log](https://github.com/HendrikRoth/node-red-contrib-oled/files/4419470/2020-04-01T08_03_58_120Z-debug.log)

**Comment by DaveNorth866** [comment]
I had same problem, issue was i2c nodes will not install if node.js is v12. . . from your log you have node v12.16.1 problem exists for node-red-contrib-oled and also node-red-contrib-i2c

I fix the issue by rolling node back to node.js to v8.11.3 I knew this version worked because I have a OLED working on an older pi with this version, Rolling back the to v8.11.2 has no detrimental problems with the rest of node-red as node v8 is supported.

sudo npm install -g n
then enter following:
sudo n 8.11.3
PATH="$PATH"
sudo reboot
then check node.js is node v8.11.3
node -v

Hope it helps

**Comment by Inxession** [comment]
Thank You DaveNorth866

The Solution works great.

Hope though, to get an up to Date Version from the OLED Node to be up to Date.

**Comment by HendrikRoth** [comment]
I updated the npm dependencies, could someone confirm if there were no breaking changes? i have no hardware at the moment to test it.

https://github.com/HendrikRoth/node-red-contrib-oled/tree/development

**Comment by shinong** [comment]
> I updated the npm dependencies, could someone confirm if there were no breaking changes? i have no hardware at the moment to test it.
> 
> https://github.com/HendrikRoth/node-red-contrib-oled/tree/development

Hello HendrikRoth,
I pulled your code with updated dependencies and installed it locally. Works well on my RPI. 
Thank you!

**Comment by HendrikRoth** [comment]
Great thank you, then i will merge it now.
